var mapset=[[
    "x                  x",
    "x                  x",
    "x   xx          o  x",
    "x                  x",
    "x                  x",
    "x      o       x   x",
    "x         !    x   x",
    "x           xxxx   x",
    "x   !              x",
    "x                  x"],[

    "xo                ox",
    "x   xxxx           x",
    "x      x        o  x",
    "x         x        x",
    "x     xx xx        x",
    "x      o       x   x",
    "x              x   x",
    "x           x      x",
    "x   !              x",
    "x                  x"],[

    "xo                 x",
    "x                  x",
    "x   xxxx        o  x",
    "x                  x",
    "x                  x",
    "x      o       x   x",
    "x xxxxxx  xxx  xxxxx",
    "x                  x",
    "x   !              x",
    "x                  x"],[

    "x                  x",
    "x                  x",
    "x   x           o  x",
    "x      xxx         x",
    "x                  x",
    "x      o       x   x",
    "x              x   x",
    "x           xxxx   x",
    "x   !              x",
    "x                  x"],[

    "x                  x",
    "x          !       x",
    "x       !       o  x",
    "x                  x",
    "x                  x",
    "x      o       x   x",
    "x              x   x",
    "x           xxxx   x",
    "x   !              x",
    "x                  x"],[

    "x                  x",
    "x                  x",
    "x               o  x",
    "x                  x",
    "x                  x",
    "x      o           x",
    "x                  x",
    "x                  x",
    "x   !              x",
    "x                  x"],[

    "x                  x",
    "x                  x",
    "x   xxxx        o  x",
    "x                  x",
    "x                  x",
    "x      o       x   x",
    "x              x   x",
    "x           xxxx   x",
    "x   !              x",
    "x                  x"],[

    "x                  x",
    "x                  x",
    "x   xxxx        o  x",
    "x                  x",
    "x                  x",
    "x      o       xxxxx",
    "x              xoo x",
    "x           xx     x",
    "x            !     x",
    "x                  x"],[

    "x                  x",
    "x                  x",
    "x   xxxxxxxxxxxxooox",
    "x                  x",
    "x                  x",
    "x      o       x   x",
    "x              x   x",
    "x           xxxx   x",
    "x   !              x",
    "x                  x"],[

    "xoo              oox",
    "x                  x",
    "x   xxxx        o  x",
    "x                  x",
    "x                  x",
    "x      o       x   x",
    "x !!!!!   !!  !!!! x",
    "x           xxxx   x",
    "x                  x",
    "x                  x"]]
